[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = ["futures/std"]
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = { version = "0.1.0" }

cortex-m = "0.6.4"
futures     = { version = "0.3.5", default-features = false }
pin-project = { version = "1.0.2", default-features = false }
futures-intrusive = { version = "0.3.1", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}

